--?? 1. Script Oracle 19c
--Crear tabla
CREATE TABLE PRODUCTOS_J (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CATEGORIA VARCHAR2(100),
    PRECIO NUMBER(10,2),
    STOCK NUMBER
);

COMMIT;

--? 2. Insertar 60 Productos
BEGIN

FOR i IN 1..60 LOOP

    INSERT INTO PRODUCTOS_J (
        NOMBRE,
        CATEGORIA,
        PRECIO,
        STOCK
    )
    VALUES (
        'Producto_' || i,
        CASE
            WHEN MOD(i,3)=0 THEN 'Tecnologia'
            WHEN MOD(i,3)=1 THEN 'Hogar'
            ELSE 'Oficina'
        END,
        ROUND(DBMS_RANDOM.VALUE(10,500),2),
        TRUNC(DBMS_RANDOM.VALUE(1,100))
    );

END LOOP;

COMMIT;

END;
/

COMMIT;